---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freepbx
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN_SUBDOMAIN}.${SECRET_DOMAIN}"
    coredns.io/hostname: "pbx.${SECRET_DOMAIN}"
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: traefik
  rules:
    - host: "pbx.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
               name: freepbx
               port:
                 number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "pbx.${SECRET_DOMAIN}"
      secretName: ${SECRET_DOMAIN}-tls
---
apiVersion: v1
kind: Service
metadata:
  name: freepbx
  namespace: networking
spec:
  ports:
    - name: http
      port: 80
  type: ExternalName
  externalName: 10.20.30.190