---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freepbx
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN_SUBDOMAIN}.${SECRET_DOMAIN}"
    coredns.io/hostname: "pbx.${SECRET_DOMAIN}"
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: "pbx.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
               name: freepbx
               port:
                 number: 443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "pbx.${SECRET_DOMAIN}"
      secretName: ${SECRET_DOMAIN}-tls
---
apiVersion: v1
kind: Service
metadata:
  name: freepbx
  namespace: networking
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: freepbx
  namespace: networking
subsets:
  - addresses:
      - ip: "${FREEPBX_ADDR}"
    ports:
      - name: http
        port: 80
        protocol: TCP
      - name: https
        port: 443
        protocol: TCP

