---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trinitycore-world-claim-v1
  namespace: etc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: nfs-client
