---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/ansible"
  K3S_PRIMARY_MASTER_NODE_USERNAME: "kashall"
  K3S_PRIMARY_MASTER_NODE_ADDR: "10.20.30.6"
  K3S_LB_ADDR: "10.0.0.1"

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/kubeconfig"

includes:
  ansible: .taskfiles/ansible.yml
  flux: .taskfiles/flux.yml
  format: .taskfiles/format.yml
  lint: .taskfiles/lint.yml
  pre-commit: .taskfiles/pre-commit.yml

tasks:
  update-deps:
    - task: update-deps:ansible
    - task: update-deps:pre-commit

  update-deps:ansible:
    desc: install/upgrade ansible deps
    dir: ansible
    cmds:
      - "ansible-galaxy install -r requirements.yml --roles-path ~/.ansible/roles --force"
      - "ansible-galaxy collection install -r requirements.yml --collections-path ~/.ansible/collections --force"

  update-deps:pre-commit:
    desc: install/upgrade pre-commit deps
    cmds:
      - pre-commit autoupdate
      - pre-commit install --install-hooks

  kubeconfig:
    desc: Remotely fetch kubeconfig from Kubernetes
    cmds:
      - rsync --verbose --progress --partial --rsync-path="sudo rsync" {{.K3S_PRIMARY_MASTER_NODE_USERNAME}}@{{.K3S_PRIMARY_MASTER_NODE_ADDR}}:/etc/rancher/k3s/k3s.yaml "{{.CLUSTER_DIR}}/kubeconfig"
      - sed -i '' 's/127.0.0.1/{{.K3S_LB_ADDR}}/g' "{{.CLUSTER_DIR}}/kubeconfig"
      - chmod go-r "{{.CLUSTER_DIR}}/kubeconfig"