---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - botkube
  - grafana
  - kube-prometheus-stack
  - loki
  - nut-exporter
  - promtail
  - pve-exporter
  - speedtest-exporter
  - snmp-exporter
  - thanos
  - unifi-poller
  - uptimerobot-heartbeat
