---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weeb-services-claim-v1
  namespace: etc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client