---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-claim
  namespace: databases
spec:
  storageClassName: longhorn 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi