---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  COREDNS_ADDR: 10.0.5.53
  #
  UNIFI_CONTROLLER: 10.0.0.1
  TRAEFIK_ADDR: 10.69.0.80
  HOME_ASSISTANT_ADDR: 10.69.0.69
  BLOCKY_ADDR: 10.69.0.53