---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.20.30.10-10.20.30.30
  #
  # Services
  #
  HOME_ASSISTANT_ADDR: 10.20.30.40
  TRAEFIK_ADDR: 10.20.30.10