# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SUPER_SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:cCd6h6NEN+poFVxUoZk=,iv:rNEmAKhVggF6TA7bbwmxWR9GggDsn9GUt3S7qQ1dssU=,tag:Gz45vlIAsWPuk7Evf0NI3Q==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:9pluj1qKLw==,iv:pJCf3xD5FI9DzealJfNXjbvbMkHo7p7FfIS7JBzY+ck=,tag:HOuiaow0E3jdR50qcHc9LA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:ygnO92Py+n7Xj+Bzt3M=,iv:Pd8vs0ZqhpePzzLoIa3wjSGPrb0mq6sLzh9GLwyZOns=,tag:D9Y8MhAdOXQKRRy5chH1Bw==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:0052,iv:5Moz/qKnAyHb13pCR8jI7fPcX0gkIGedVdBG4CzPVII=,tag:O1tvzHz9HM+docHWpU7w+A==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:3qgm0ieHjstK,iv:CGlhDpoyo5EMsmeUqPyo+jwxXNhhDTITXSfNoia7OXQ=,tag:eQ+tDOTvbwD/tjoqyDATgw==,type:str]
    SECRET_MINIO_PROMETHEUS_BEARER: ENC[AES256_GCM,data:Eu6R8sVhNTjTgDpnod1+VcDD5htgMv92p7eMKhjeGSgrUzfvRy2BROFpjOO4M0nQtqmUmn+BoZE2/GvsiiPkaI1Vipkv1BR6VFLU5P1ckT6LsXh6ljXDnawpClf2duwdexYAuZG2JphQGj5uGa/47kgF1M4fnFHKYqiBiT34Io8AT9IinVkUziDRtKJz3+TMWRxWEiZDtFoHtPuFrc/sRl/M+RpuCm4Vpqbkv/Ktr0NRfotwZkAMwB1eKrstBudoOdJ2pnIp5g==,iv:lDcGsNhkvO9XTLkhhzrzJuMx0fgLy183WjkM5wEnatM=,tag:NScSWWHkSCS9G7+7APvrJA==,type:str]
    SECRET_DOMAIN_SUBDOMAIN: ENC[AES256_GCM,data:trznDQ==,iv:X2epzYnnLsJDMMo3JRiVKytANitxiLOPj6Bq1Not/YI=,tag:lRwBQG/VHO2iARaviNnyjw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:k/0WwzUCaw==,iv:N97vuOBBKnhnD3fkeL/TbPbKxGn6U7NiPqABxtaWENw=,tag:0DCOyTLqxXx+OrI5W+Movg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FtQ48vXMDd07vWGAN6dy3NG8XLE=,iv:xzGoVlsOJxZa9E8yWFi/K4+z18q4SaVdTMyUYbbbjH8=,tag:V4+6vV71LSBgNgNpSIamPQ==,type:str]
    SECRET_TRAEFIK_TOKEN: ENC[AES256_GCM,data:B63bGEOiuNMZG4Gf3ribpSfz9fpzHaPYc8xZOI3peoc2HCPc,iv:oQdcke9J1D1V376YYu9FIlvjO5drXHMK2IyJKcfVKLE=,tag:a7lAXYSRSJ4Tt3IPGR5k6g==,type:str]
    SECRET_KURED_DISCORD_WEBHOOK: ENC[AES256_GCM,data:l/1G4jCIjL1QMnKEL0UJyrMTkw4Y2L+x8JLRXJw03AGKP4aAuwRkecm9pCkxFLzI1aVpBPsigzNMy4R4BbzYl+oGdrNvcqK1VRKk8/egSAZk1ggpZidxhbBbi6lSGdhzvx+QX2FlAU4OG8iY71X5CbKLFls7iABMOLeySFuJ,iv:LLyZJIVflXmPUi07jNcQvaR1q5OB3oKFRjS0TzclKKA=,tag:JHZI4sT1gq4zslacOYw4ag==,type:str]
    SECRET_PROMETHEUS_DISCORD_WEBHOOK: ENC[AES256_GCM,data:EknL7U3+IW2i1Dv4HDJBLUIY9m0L2G40JiLL2dXiVOYvqT/IFrX3mIcnkWLuHNDnaHDKWuUC9M+YFByzVaffehSFyeVxrYJHVLN8litUpCVv9yufvDEeuS82Wc+vpAafM6XBKZ+SXIZZ9NarHxNRhDF9K3m71M+3OrMhjCtW,iv:Mz9XeLI+hksykIZzWjmZGBn/gwmgBnnpRxr24Q3YpH8=,tag:pzHsEvvvgRBApPZt462pBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-04T02:39:12Z"
    mac: ENC[AES256_GCM,data:83RFBrk549hIejUqAjStQt8GdfAZWPDFf4Ulij8a0qsRBjxx/HDRqYA8k2c/9gQOt+l8E5xlOcR4uZNUSaZ8jHRE5SS2Oafwc58GbXyJ6bIFh03uQbHRgNRqQZvmAzuo84fyAiMjnW5Bo0EbWIVF8jTRj0p+9y4KvqOaZ9O4Cfs=,iv:XEeybHYvPkDFR9e/FQqz3vkeleJ833h9lgQthjDsLm0=,tag:XyPrIYRdj8MDkwikueNybA==,type:str]
    pgp:
        - created_at: "2021-08-24T06:12:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxpELGKypk39ARAAnQjQZPdWBJeqFC2DzmGormHwxFoRwYc1OFi3ZZTbFEBs
            bdsoYpBUjWPgooT/0ehlTwmsE99hWCoAFEqUjIyIciwGKKuI7s7ORz6zKrX2ffvz
            ATb+HMEcNgyH/ex9mli1+Y8rh0ZSAEI4wwhRCnhY0eA/yIf9pu2Q1M63sV2OGzJd
            F4YMND/nre4HKfiqPZohbCvoA2Oi6Y4zQkgA+FcKMShc91+rXh57IxaG1q3LRUCX
            eVcSvi64lCt3AEoOEMn1hPKujPev+ppsdOuCwhjQlZ3cScXq76Jl3UE1xzWXUD++
            YxpYdYSEpPnR9uZm4kdectfdlf7ofzt5ZPqU3RsIE/P+H0nckY3soRYRcPtw5Pck
            3Gtn+YaUm4oS0092YZjQSm3tgeag/ffH9MFXS3dt8iKEluz8prywyhuWAG8Ieea/
            dGbc7hYlK31fgyYA+SuGYsCXcZut3UxnTxre3ibBsCHrYivFd+dVmMeKkWV53BcI
            hSfOlF4kObpJ3VHLecPYl0jUPUfgYUbblEAsmNlzMvmnGcgDNPC7IbgBlvy8+c5t
            wJx3MeshqH50WYfToRiiyjg+aj9kZTE37ppMHQxGQs7D41QIK6eOntPzHEsCwsTA
            eYwkMoAhNaSNDrvP5yskEMeMnumyRHe9oKCkxG7e6WNA6dhjAM8Uh7HERsHx+QTS
            XgEJEHwh4ZHp2wZ3jNfzM5i/mrFnZcYmFH6tCta/6UnEG1kQPWtYoH05yjaqc4ou
            AnFgaZHNV4ygIdjD5ATZO3xvZYShvU/843YC7MrnNdwDOs5E5cBRGtsTZ5PjwjQ=
            =T5d9
            -----END PGP MESSAGE-----
          fp: 0FDCB6725CDC2E9EFC647D95158E6CE58CC276A3
        - created_at: "2021-08-24T06:12:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3Lpr5MOghdnAQ//UmhpW0N7ej9VBRckyBM6rrF0/GwhZJoeWXadeB8ifKW6
            byX4oqZfvGYxQserw0Urb1qmIB+RF17Cpye4ii089byaCiEeyMMVM2Q9ozKnALla
            A1b+auW/dG7flm/ztsKLn94pGc8bD85Q//exKZWVbMzq1Xm+bAYG+qnABQWeCJfh
            jzles/nNMRjajQbnVgnxgvopx9rFumbS3rr8Z7gDBeL05wAIAmG0aj4JNWb3YwNM
            mVL0iLSe1IUGiWX4alGTdpkakeLf5NOS89LniI0J2pxvZMAEie51Wkh7W2dlg5A0
            df/8JCsZBQov+a/321rstm51GUpTkqZ8aj+3BBun3CNdybCLpNwCnea8XacG5qjP
            9gtUAQkclc4VkPza2VpLQNiOrEWyfl0R5+ciZcfaiLti/rO5j8ccvJK2asWJsfzo
            QRhrZLIGoXEGuLi7Klt3l4Gd1jFKPUozIdsef4ngr2Ot72TR9Gya4oEM47FVWRPs
            8XQ9bAaOITKq8hmvICnxC+UkKCaSzJSTBf5T1mhuaIGU9xmw/jN/lhA2uBK28xZY
            pNPgFbc4+10R/E6fRYdRwqvthSfm6D5ljyQI29iZaPYATVggWhy8EHDfYZoiSXXs
            MAYqOJljM82rM6+u/Zz6rsoehwPTmSuNnVBhdg+W+yXGE0k/pZnAEKjVLjVQX/DS
            XgGQc6dcn1okLL2OiTliFNNKIFPTOzmlRXIMI5rVYKnkqz9ZrvZKx10oEBqGzVGd
            /M/n0AU5EAkey8aEglrHw4lliZysdhI7TEBlI0/5tMt7O4nlyJORibxmh21CaxI=
            =x30w
            -----END PGP MESSAGE-----
          fp: AF3D8C1E0EC5C65F713609D9401F0F07454134DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
