---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-spotify-db-claim
  namespace: etc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
