---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cluster-redirect
  namespace: networking
spec:
  redirectRegex: # kami\.gg
    regex: "^(?:https?:\/\/)?(?:www\.)?${SECRET_DOMAIN/./\.}(\/.*)?$"
    replacement: "https://github.com/kashalls/home-cluster"
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: main-redirect
  namespace: networking
spec:
  redirectRegex:
    regex: "^(?:https?:\/\/)?(?:www\.)?jordanjones\.org(\/.*)?$"
    replacement: "https://github.com/kashalls"
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: root-domains
  namespace: networking
spec:
  chain:
    middlewares:
      - name: main-redirect
      - name: cluster-redirect