---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-io-config-v1
  namespace: home
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
