---
apiVersion: v1
kind: Service
metadata: 
  name: trinity-auth-service
  namespace: etc
spec:
  ports:
    - port: 3724
      targetPort: 3724
  selector:
    app: trinity-auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trinitycore-auth
  namespace: etc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trinity-auth
  template:
    metadata:
      labels:
        app: trinity-auth
    spec:
      containers:
        - name: trinity-auth
          image: docker.io/timothystewart6/botsplusplus-authserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3724
          env:
            DB_HOST: "mariadb.databases.svc.cluster.local"
            DB_PORT: 3306
          volumeMounts:
            - mountPath: /opt/trinitycore
              name: auth-server-storage
      volumes:
        - name: auth-server-storage
          persistentVolumeClaim:
            claimName: trinitycore-auth-claim-v1
