---
kubernetes:
  children:
    master:
      hosts:
        k8s-master-01:
          ansible_host: 10.20.30.6
      vars:
        ansible_user: kashall
    worker:
      hosts:
        k8s-worker-01:
          ansible_host: 10.20.30.3
        k8s-worker-02:
          ansible_host: 10.20.30.4
        k8s-worker-03:
          ansible_host: 10.20.30.7
      vars:
        ansible_user: kashall
